require("profke.plugins.adwaita-nvim")
require("profke.plugins.conform")
require("profke.plugins.mini-pairs")
require("profke.plugins.git-blame")
require("profke.plugins.lazygit")
require("profke.plugins.mason")
require("profke.plugins.lspconfig")
require("profke.plugins.persistance")
require("profke.plugins.tasks")
require("profke.plugins.telescope")
require("profke.plugins.treesitter")
require("profke.plugins.which-key")
-- require("profke.plugins.minuet-ai")
-- require("profke.plugins.blink-cmp")
-- require("profke.plugins.codecompanion")
require("profke.plugins.yazi")
